image:
  repository: rancher/rancher-webhook
  tag: latest
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""
  hostNetwork: false

capi:
  enabled: false

mcm:
  enabled: true

preDelete:
  enabled: true
  image:
    repository: rancher/kubectl
    tag: v1.20.2
